### ISSUE TITLE
mocha-typescript -> testdeck

### ISSUE THREAD

**Issue by iamolegga** [sskorol/ts-test-decorators#11]
Hi, tried to upgrade `mocha-typescript` to `testdeck` but it's not working:
```
➜  mocha-allure2-example master ✗ yarn test
yarn run v1.22.4
$ tsc && yarn clean && sleep 1 && multi='progress=- mocha-allure2-reporter=-' mocha -R mocha-multi --opts ./mocha.opts
$ rimraf ./report ./allure-results



  0 passing (3ms)

✨  Done in 3.07s.
```

repo https://github.com/iamolegga/mocha-allure2-example and diff to origin: https://github.com/iamolegga/mocha-allure2-example/commit/f121f09ea950dd3d20d78d5cbfd3452e4924bf9b

**Comment by sskorol** [comment]
Yes, it's much trickier than just a simple dependency update. I can push the latest version based on this PR https://github.com/allure-framework/allure-js/pull/138. But you'll have to build and install `allure-js` from my branch then. I'm not yet sure if we can find a consensus with a main reviewer. There's a concern around global container usage instead of a Mocha-centric `allure` variable. I totally accept some of the described points, but we have to find a compromise or a better design approach.

Anyway, if you're good to build everything by your own, I'll push latest updates.

**Comment by iamolegga** [comment]
Ok, we are good for now anyway, I just created this issue to track the moment, when we can update.

By the way, I'm interested in your opinion on dropping `dotenv` package off and provide setters for `pmsUrl` and `tmsUrl`, so end users could figure it out how to get it (from env, hardcode it, etc). If you are ok with that I could handle it and create PR on that, but it will be breaking change

**Comment by sskorol** [comment]
Sounds good. Just make sure you provide default values if a user forgot to set them.

**Comment by iamolegga** [comment]
Ok! 👍
